### ISSUE TITLE
fury-adapter-swagger upgrade causes Type Error

### ISSUE THREAD

**Issue by Farga83** [apiaryio/dredd-transactions#93]
The most recent release included an upgrade to fury and minim dependencies. With those changes I get the following error when trying to run dredd.

```
/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:52
      element.parent = this;
                     ^

TypeError: Cannot assign to read only property 'parent' of object '#<AuthScheme>'
    at constructor.<anonymous> (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:52:22)
    at Array.forEach (<anonymous>:null:null)
    at constructor.forEach (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/array-slice.js:58:19)
    at constructor.freeze (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:51:19)
    at constructor.<anonymous> (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:53:15)
    at Array.forEach (<anonymous>:null:null)
    at constructor.forEach (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/array-slice.js:58:19)
    at constructor.freeze (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:51:19)
    at constructor.<anonymous> (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:53:15)
    at Array.forEach (<anonymous>:null:null)
    at constructor.forEach (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/array-slice.js:58:19)
    at constructor.freeze (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:51:19)
    at HttpTransaction.freeze (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:48:23)
    at Transition.<anonymous> (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:53:15)
    at Array.forEach (<anonymous>:null:null)
    at constructor.forEach (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/array-slice.js:58:19)
    at Transition.freeze (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:51:19)
    at Resource.<anonymous> (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:53:15)
    at Array.forEach (<anonymous>:null:null)
    at constructor.forEach (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/array-slice.js:58:19)
    at Resource.freeze (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:51:19)
    at Category.<anonymous> (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:53:15)
    at Array.forEach (<anonymous>:null:null)
    at constructor.forEach (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/array-slice.js:58:19)
    at Category.freeze (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:51:19)
    at ParseResult.<anonymous> (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:53:15)
    at Array.forEach (<anonymous>:null:null)
    at constructor.forEach (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/array-slice.js:58:19)
    at ParseResult.freeze (/usr/local/lib/node_modules/dredd/node_modules/minim/lib/primitives/element.js:51:19)
    at /usr/local/lib/node_modules/dredd/node_modules/dredd-transactions/lib/parse.js:42:19
    at /usr/local/lib/node_modules/dredd/node_modules/fury/lib/fury.js:169:13
    at complete (/usr/local/lib/node_modules/dredd/node_modules/fury-adapter-swagger/lib/parser.js:258:20)
    at /usr/local/lib/node_modules/dredd/node_modules/fury-adapter-swagger/lib/parser.js:280:17
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

To reproduce, simply do a fresh install of dredd as outlined here
http://dredd.readthedocs.io/en/latest/installation.html and run dredd against a swagger.yaml file.

To work around the issue, manually update dredd/packages.json restricting the version.

I believe the commit introducing the issue is https://github.com/apiaryio/dredd-transactions/commit/ea91dc6

**Comment by antkazam** [comment]
Thanks for opening! 👍 This is affecting me today as well.

**Comment by kylef** [comment]
Could either of you please share your Swagger file (or a smaller variant that can reproduce the problem). It isn't just any Swagger document that would cause the problem. If you don't want to post it here publicly feel free to email it to me at kyle.fuller@oracle.com and I should be able to fix it shortly, the problem most likely in fury-adapter-swagger.

Regards,

Kyle

**Comment by Farga83** [comment]
[petstore.yaml.zip](https://github.com/apiaryio/dredd-transactions/files/1231960/petstore.yaml.zip)

Here's what makes it fail

```
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

security:
  - Bearer: []
```

**Comment by kylef** [comment]
Thanks @Farga83, I've prepared a fix in https://github.com/apiaryio/fury-adapter-swagger/pull/120. Should get this out shortly.

**Comment by honzajavorek** [comment]
This has been fixed in the Fury adapter, but not in Dredd Transactions yet.
